apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aoa-argoset-app2
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - path: stage
        - path: prod
  template:
    metadata:
      name: "app2-{{path}}"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/hadi2f244/aoa-argoset-app2.git
        targetRevision: HEAD
        path: "overlays/{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path}}"
      syncPolicy:
        syncOptions:
        - CreateNamespace=true